# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  core6502_config = debug
endif
ifeq ($(config),release)
  core6502_config = release
endif

PROJECTS := core6502

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

core6502:
ifneq (,$(core6502_config))
	@echo "==== Building core6502 ($(core6502_config)) ===="
	@${MAKE} --no-print-directory -C . -f core6502.make config=$(core6502_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f core6502.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   core6502"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"